version: '3.9'

services:
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
      args:
        INSTALL_MODE: dev
    environment:
      WORKER_VNC_WS_BASE: ws://localhost:6900
      WORKER_VNC_HTTP_BASE: http://localhost:6900
    ports:
      - '8080:8080'
      - '6900:6900'
      - '5900:5900'
    volumes:
      - ./worker:/opt/app

  control-plane:
    build:
      context: .
      dockerfile: docker/Dockerfile.control
      args:
        INSTALL_MODE: dev
    environment:
      CONTROL_WORKERS: '[{"name":"local","url":"http://worker:8080","vnc_ws":"ws://localhost:6900","vnc_http":"http://localhost:6900"}]'
    depends_on:
      - worker
    ports:
      - '9000:9000'
    volumes:
      - ./control-plane:/opt/app

  ui:
    image: node:20
    working_dir: /app
    environment:
      VITE_API_ORIGIN: http://control-plane:9000
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - control-plane
    ports:
      - '5173:5173'
    volumes:
      - ./ui:/app
      - ui_node_modules:/app/node_modules

volumes:
  ui_node_modules:
