[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = '''
(
    /(
        \.git
        | \.github
        | \.venv
        | build
        | dist
        | node_modules
        | ui/node_modules
        | ui/dist
    )/
)
'''

[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = [
    "build",
    "dist",
    "node_modules",
    "ui/node_modules",
    "ui/dist",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "B",
    "UP",
]
ignore = [
    "B008",
]

