global:
  imageRegistry: ""
  imagePullSecrets: []

control:
  replicas: 1
  image:
    repository: camofleet-control
    tag: latest
    pullPolicy: IfNotPresent
  podAnnotations: {}
  resources: {}
  extraEnv: []
  service:
    type: ClusterIP
    port: 9000
  publicApiPrefix: /api
  config:
    workers:
      - name: worker-headless
        url: http://camofleet-camo-fleet-worker:8080
        supports_vnc: false
      - name: worker-vnc
        url: http://camofleet-camo-fleet-worker-vnc:8080
        supports_vnc: true
        vnc_ws: wss://camofleet.services.synestra.tech/vnc/{port}/websockify
        vnc_http: https://camofleet.services.synestra.tech/vnc/{port}/vnc.html

ui:
  replicas: 1
  image:
    repository: camofleet-ui
    tag: latest
    pullPolicy: IfNotPresent
  podAnnotations: {}
  resources: {}
  controlHost: ""
  service:
    type: ClusterIP
    port: 80

worker:
  enabled: true
  replicas: 1
  runnerImage:
    repository: camofleet-runner
    tag: latest
    pullPolicy: IfNotPresent
  runnerResources: {}
  runnerExtraEnv: []
  image:
    repository: camofleet-worker
    tag: latest
    pullPolicy: IfNotPresent
  podAnnotations: {}
  resources: {}
  runnerPort: 8070
  service:
    type: ClusterIP
    port: 8080
  supportsVnc: false
  sessionDefaults:
    headless: true
  extraEnv: []

workerVnc:
  enabled: true
  replicas: 1
  runnerImage:
    repository: camofleet-runner-vnc
    tag: latest
    pullPolicy: IfNotPresent
  runnerResources: {}
  runnerExtraEnv: []
  image:
    repository: camofleet-worker
    tag: latest
    pullPolicy: IfNotPresent
  podAnnotations: {}
  resources: {}
  runnerPort: 8070
  service:
    type: ClusterIP
    port: 8080
  vncPortRange:
    ws:
      min: 6900
      max: 6904
    raw:
      min: 5900
      max: 5904
  traefikService:
    enabled: false
  extraEnv: []
  sessionDefaults: {}
