apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: camofleet
  namespace: camofleet
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`camofleet.services.synestra.tech`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: camofleet-control
          namespace: camofleet
          port: 9000
    - match: Host(`camofleet.services.synestra.tech`) && PathPrefix(`/vnc`)
      kind: Rule
      services:
        - name: camofleet-vnc-gateway
          namespace: camofleet
          port: 6080
    - match: Host(`camofleet.services.synestra.tech`)
      kind: Rule
      priority: 1
      services:
        - name: camofleet-ui
          namespace: camofleet
          port: 80
  tls:
    secretName: camofleet-services-tls
