{{- if and .Values.traefik.enabled .Values.traefik.middleware.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ default (printf "%s-kc-auth" (include "camofleet.ui.fullname" .)) .Values.traefik.middleware.nameOverride }}
  labels:
{{ include "camofleet.labels" . | indent 4 }}
spec:
  plugin:
    keycloakopenid:
      {{- $cfg := .Values.traefik.middleware.plugin.keycloakopenid -}}
      {{- if $cfg.keycloakURL }}
      keycloakURL: {{ $cfg.keycloakURL | quote }}
      {{- end }}
      {{- if $cfg.keycloakRealm }}
      keycloakRealm: {{ $cfg.keycloakRealm | quote }}
      {{- end }}
      {{- if $cfg.clientID }}
      clientID: {{ $cfg.clientID | quote }}
      {{- end }}
      {{- if $cfg.clientSecretFile }}
      clientSecretFile: {{ $cfg.clientSecretFile | quote }}
      {{- end }}
      {{- if $cfg.scope }}
      scope: {{ $cfg.scope | quote }}
      {{- end }}
      {{- if $cfg.userHeaderName }}
      userHeaderName: {{ $cfg.userHeaderName | quote }}
      {{- end }}
      {{- if $cfg.userClaimName }}
      userClaimName: {{ $cfg.userClaimName | quote }}
      {{- end }}
      {{- $ignore := $cfg.ignorePathPrefixes }}
      {{- if $ignore }}
      {{- if kindIs "string" $ignore }}
      ignorePathPrefixes: {{ $ignore | quote }}
      {{- else }}
      ignorePathPrefixes: {{ join "," $ignore | quote }}
      {{- end }}
      {{- end }}
{{- end }}
