{{- if and .Values.traefik.enabled .Values.traefik.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ default (include "camofleet.ui.fullname" .) .Values.traefik.ingressRoute.nameOverride }}
  labels:
{{ include "camofleet.labels" . | indent 4 }}
spec:
  entryPoints:
  {{- range .Values.traefik.ingressRoute.entryPoints }}
    - {{ . | quote }}
  {{- end }}
  routes:
    - kind: Rule
      {{- $host := default .Values.ingress.host .Values.traefik.ingressRoute.host -}}
      {{- $path := default "/" .Values.traefik.ingressRoute.pathPrefix -}}
      {{- if and $host $path }}
      match: Host(`{{ $host }}`) && PathPrefix(`{{ $path }}`)
      {{- else if $host }}
      match: Host(`{{ $host }}`)
      {{- else }}
      match: PathPrefix(`{{ $path }}`)
      {{- end }}
      {{- $autoMiddlewareName := "" -}}
      {{- if .Values.traefik.middleware.enabled }}
      {{- $autoMiddlewareName = default (printf "%s-kc-auth" (include "camofleet.ui.fullname" .)) .Values.traefik.middleware.nameOverride -}}
      {{- end }}
      {{- $hasAdditional := gt (len .Values.traefik.ingressRoute.additionalMiddlewares) 0 -}}
      {{- if or $autoMiddlewareName $hasAdditional }}
      middlewares:
        {{- if $autoMiddlewareName }}
        - name: {{ $autoMiddlewareName }}
        {{- end }}
        {{- range .Values.traefik.ingressRoute.additionalMiddlewares }}
          {{- if kindIs "string" . }}
        - name: {{ . }}
          {{- else }}
        - name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      services:
        - name: {{ include "camofleet.ui.fullname" . }}
          port: {{ .Values.ui.service.port }}
  {{- if .Values.traefik.ingressRoute.tls.enabled }}
  tls:
    {{- with .Values.traefik.ingressRoute.tls.certResolver }}
    certResolver: {{ . | quote }}
    {{- end }}
    {{- $secret := default .Values.ingress.tls.secretName .Values.traefik.ingressRoute.tls.secretName }}
    {{- if $secret }}
    secretName: {{ $secret | quote }}
    {{- end }}
  {{- end }}
{{- end }}
