{{- $ns := .Values.namespace.name -}}
{{- $releaseNamespace := coalesce .Release.Namespace $ns -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: camofleet-ui-nginx
  namespace: {{ $releaseNamespace }}
  labels:
    app: camofleet-ui
    release: {{ .Release.Name }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location /api/ {
            proxy_pass http://camofleet-control:{{ int .Values.control.service.port }}/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 3600;
        }

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
