{{- $ns := .Values.namespace.name -}}
{{- $releaseNamespace := coalesce .Release.Namespace $ns -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camofleet-worker
  namespace: {{ $releaseNamespace }}
  labels:
    app: camofleet-worker
    release: {{ .Release.Name }}
    camofleet-role: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: camofleet-worker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: camofleet-worker
        release: {{ .Release.Name }}
        camofleet-role: worker
    spec:
      containers:
        - name: runner
          image: {{ include "camofleet.image" (dict "Values" .Values "repository" .Values.images.workerRunner.repository "tag" .Values.images.workerRunner.tag) }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
            - name: RUNNER_PORT
              value: {{ printf "%d" (int .Values.worker.runnerPort) | quote }}
          ports:
            - containerPort: {{ int .Values.worker.runnerPort }}
              name: runner-http
        - name: worker
          image: {{ include "camofleet.image" (dict "Values" .Values "repository" .Values.images.worker.repository "tag" .Values.images.worker.tag) }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
            - name: WORKER_RUNNER_BASE_URL
              value: http://localhost:{{ .Values.worker.runnerPort }}
            - name: WORKER_SUPPORTS_VNC
              value: "false"
          ports:
            - containerPort: {{ int .Values.worker.service.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: camofleet-worker
  namespace: {{ $releaseNamespace }}
  labels:
    app: camofleet-worker
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.worker.service.type }}
  selector:
    app: camofleet-worker
    release: {{ .Release.Name }}
  ports:
    - port: {{ int .Values.worker.service.port }}
      targetPort: http
      name: http
