{{- if .Values.workerVnc.enabled }}
{{- $rawMin := int .Values.workerVnc.vncPortRange.raw.min }}
{{- $rawMax := int .Values.workerVnc.vncPortRange.raw.max }}
{{- $wsMin := int .Values.workerVnc.vncPortRange.ws.min }}
{{- $wsMax := int .Values.workerVnc.vncPortRange.ws.max }}
{{- $httpPort := int .Values.workerVnc.service.port }}
{{- if gt $wsMin $wsMax }}
  {{- fail (printf "workerVnc.vncPortRange.ws.min (%d) must be <= ws.max (%d)" $wsMin $wsMax) }}
{{- end }}
{{- if gt $rawMin $rawMax }}
  {{- fail (printf "workerVnc.vncPortRange.raw.min (%d) must be <= raw.max (%d)" $rawMin $rawMax) }}
{{- end }}
{{- if and (ge $httpPort $rawMin) (le $httpPort $rawMax) }}
  {{- fail (printf "workerVnc.service.port (%d) overlaps raw range %d-%d" $httpPort $rawMin $rawMax) }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "camofleet.workerVnc.fullname" . }}
  labels:
    app: {{ include "camofleet.workerVnc.fullname" . }}
{{ include "camofleet.labels" . | indent 4 }}
spec:
  type: {{ .Values.workerVnc.service.type }}
  selector:
    app: {{ include "camofleet.workerVnc.fullname" . }}
  ports:
    - port: {{ .Values.workerVnc.service.port }}
      targetPort: http
      name: http
{{- $wsUpper := int (add $wsMax 1) }}
{{- range $port := untilStep $wsMin $wsUpper 1 }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      name: {{ printf "vnc-ws-%d" $port }}
{{- end }}
{{- $rawUpper := int (add $rawMax 1) }}
{{- range $port := untilStep $rawMin $rawUpper 1 }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      name: {{ printf "vnc-raw-%d" $port }}
{{- end }}
{{- end }}
